openapi: 3.0.0
info:
  title: ProductPublic
  version: 1.0.0
servers:
  - url: https://wirausahaanakulbi-server.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /users:
    get:
      tags:
        - default
      summary: GetAllUsers
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/:
    get:
      tags:
        - default
      summary: UserLogin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /registration:
    post:
      tags:
        - default
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Gading Khairlambang
                npm: 714220007
                numberPhone: '0812344553'
                password: admin12345
                confirmPassword: admin12345
                role: Seller
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: 714220005
                password: admin12345
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-admin:
    get:
      tags:
        - default
      summary: GetAdminCategory
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostAdminCategory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: Peralatan
                icon: fa-solid-fa-equipment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-admin/{id}:
    get:
      tags:
        - default
      summary: GetAdminCategoryByID
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: PutAdminCategory
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: Equipment
                icon: fa-solid-fa-equipment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteAdminCategory
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /product:
    get:
      tags:
        - default
      summary: GetProductAll
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_user: 14
                id_category: 1
                product_name: Pizza
                price: 7000
                photo: 2521.jpg
                stock: 100
                detail: Posted detailed description of the product
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /product/{id}:
    get:
      tags:
        - default
      summary: GetProductByID
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: PutProduct
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_user: 14
                id_category: 1
                product_name: Pizza
                price: 7000
                photo: 2521.jpg
                stock: 100
                detail: Updated detailed description of the product
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteProduct
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /product-seller:
    get:
      tags:
        - default
      summary: GetProductSeller
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category:
    get:
      tags:
        - default
      summary: GetAllCategory
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostCategorySeller
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_category_admin: 5
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category-seller:
    get:
      tags:
        - default
      summary: GetCategorySeller
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /category/{id}:
    put:
      tags:
        - default
      summary: PutCategorySeller
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_category_admin: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteCategorySeller
      parameters:
        - in: path
          name: id
          required: true
          description: ID
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /address:
    get:
      tags:
        - default
      summary: GetAddressUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostAddressUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                province_id: 11
                regency_id: 1101
                district_id: 1101010
                village_id: 1101010001
                patokan: JL Latiung No 24
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
